// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DockerServiceClient is the client API for DockerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerServiceClient interface {
	RunContainer(ctx context.Context, in *DockerContainerSpec, opts ...grpc.CallOption) (DockerService_RunContainerClient, error)
}

type dockerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerServiceClient(cc grpc.ClientConnInterface) DockerServiceClient {
	return &dockerServiceClient{cc}
}

func (c *dockerServiceClient) RunContainer(ctx context.Context, in *DockerContainerSpec, opts ...grpc.CallOption) (DockerService_RunContainerClient, error) {
	stream, err := c.cc.NewStream(ctx, &DockerService_ServiceDesc.Streams[0], "/docker.DockerService/RunContainer", opts...)
	if err != nil {
		return nil, err
	}
	x := &dockerServiceRunContainerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DockerService_RunContainerClient interface {
	Recv() (*DockerContainerResult, error)
	grpc.ClientStream
}

type dockerServiceRunContainerClient struct {
	grpc.ClientStream
}

func (x *dockerServiceRunContainerClient) Recv() (*DockerContainerResult, error) {
	m := new(DockerContainerResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DockerServiceServer is the server API for DockerService service.
// All implementations must embed UnimplementedDockerServiceServer
// for forward compatibility
type DockerServiceServer interface {
	RunContainer(*DockerContainerSpec, DockerService_RunContainerServer) error
	mustEmbedUnimplementedDockerServiceServer()
}

// UnimplementedDockerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDockerServiceServer struct {
}

func (UnimplementedDockerServiceServer) RunContainer(*DockerContainerSpec, DockerService_RunContainerServer) error {
	return status.Errorf(codes.Unimplemented, "method RunContainer not implemented")
}
func (UnimplementedDockerServiceServer) mustEmbedUnimplementedDockerServiceServer() {}

// UnsafeDockerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerServiceServer will
// result in compilation errors.
type UnsafeDockerServiceServer interface {
	mustEmbedUnimplementedDockerServiceServer()
}

func RegisterDockerServiceServer(s grpc.ServiceRegistrar, srv DockerServiceServer) {
	s.RegisterService(&DockerService_ServiceDesc, srv)
}

func _DockerService_RunContainer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DockerContainerSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DockerServiceServer).RunContainer(m, &dockerServiceRunContainerServer{stream})
}

type DockerService_RunContainerServer interface {
	Send(*DockerContainerResult) error
	grpc.ServerStream
}

type dockerServiceRunContainerServer struct {
	grpc.ServerStream
}

func (x *dockerServiceRunContainerServer) Send(m *DockerContainerResult) error {
	return x.ServerStream.SendMsg(m)
}

// DockerService_ServiceDesc is the grpc.ServiceDesc for DockerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docker.DockerService",
	HandlerType: (*DockerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunContainer",
			Handler:       _DockerService_RunContainer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docker.proto",
}
